config/routes.rb
Rails.application.routes.draw do
  get 'home/index'
  get 'facebook/token'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/facebook_controller.rb
class FacebookController < ApplicationController
  def token
    # render json: params
    token = params[:token]
    url = "https://graph.facebook.com/me"
    url += "?access_token=#{token}"
    url += "&fields=name,email"

    profile = HTTParty.get(url).parsed_response
    render json: profile
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/facebook_helper.rb
module FacebookHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/index.html.erb
<h1>Facebook OAuth</h1>
<!-- <div class="fb-login-button" data-max-rows="1" data-size="xlarge" data-show-faces="false" data-auto-logout-link="false"></div> -->
<!-- <%= link_to "Steal Token", facebook_token_path, id: 'token_transfer_link' %> -->
<br>
<%= link_to 'Real Login', facebook_token_path, id: 'login-link' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>OauthExample2</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>


</html>